#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M

#Gradle
org.gradle.jvmargs=-Xmx3072M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
org.gradle.caching=true
# Use JDK 21 for Gradle builds
org.gradle.java.home=/Users/denis.ambatenne/Library/Java/JavaVirtualMachines/jbr-21.0.5/Contents/Home

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true